### ISSUE TITLE
Error in installing

### ISSUE THREAD

**Issue by MohammedSalahadin** [mainio/decidim-module-plans#47] opened 2021-01-08 15:38 UTC
After adding the gem "decidim-plans" to Gemfile.

With trying bundle I got this error:
```
Bundler could not find compatible versions for gem "decidim-proposals":
  In snapshot (Gemfile.lock):
    decidim-proposals (= 0.23.1)

  In Gemfile:
    decidim-dev (= 0.23.1) was resolved to 0.23.1, which depends on
      decidim (= 0.23.1) was resolved to 0.23.1, which depends on
        decidim-proposals (= 0.23.1)

    decidim-plans was resolved to 0.15.1, which depends on
      decidim-proposals (~> 0.15.0)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```
I have tried **bundle update** and bundle update **decidim-plans** and got the same error

**Comment by ahukkanen** [comment] 2023-07-02 19:24
Duplicate of #43. See the last comment in that issue.

**Closed by ahukkanen** 2023-07-02 19:24 UTC
